alias: "Smart Floor Lamp: Midnight Step Down"
description: "Starts at 00:00, Slowly fades and turned off in 20 minutes."
trigger:
  - platform: time
    at: "00:00:00"
action:
  - repeat:
      count: 100
      sequence:
        - service: light.turn_on
          target:
            entity_id: light.smart_floor_lamp_switch
          data:
            brightness_step_pct: -1
        - delay: "00:00:12"
  - service: light.turn_off
    target:
      entity_id: light.smart_floor_lamp_switch
